#%RAML 0.8
---
title: GitHub API
version: v3
baseUri: https://api.github.com
securitySchemes:
    - oauth_2_0:
        type: OAuth 2.0
        describedBy:
            headers:
                Authorization:
                    type: string
/user:
  get:
    responses:
      200
/users:
  /{userId}:
    get:
      uriParameters:
        userId:
          type: integer
